//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Projects/Visual Studio/Addmusic2/Addmusic2/Addmusic2/Mml.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMmlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MmlBaseListener : IMmlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.song"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSong([NotNull] MmlParser.SongContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.song"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSong([NotNull] MmlParser.SongContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.songElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSongElement([NotNull] MmlParser.SongElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.songElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSongElement([NotNull] MmlParser.SongElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.specialDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialDirective([NotNull] MmlParser.SpecialDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.specialDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialDirective([NotNull] MmlParser.SpecialDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.samples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSamples([NotNull] MmlParser.SamplesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.samples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSamples([NotNull] MmlParser.SamplesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.samplesList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSamplesList([NotNull] MmlParser.SamplesListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.samplesList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSamplesList([NotNull] MmlParser.SamplesListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.instruments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruments([NotNull] MmlParser.InstrumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.instruments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruments([NotNull] MmlParser.InstrumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NamedInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedInstrumentListItem([NotNull] MmlParser.NamedInstrumentListItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedInstrumentListItem([NotNull] MmlParser.NamedInstrumentListItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstrumentListItem([NotNull] MmlParser.InstrumentListItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstrumentListItem([NotNull] MmlParser.InstrumentListItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NoiseInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoiseInstrumentListItem([NotNull] MmlParser.NoiseInstrumentListItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NoiseInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoiseInstrumentListItem([NotNull] MmlParser.NoiseInstrumentListItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.spc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpc([NotNull] MmlParser.SpcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.spc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpc([NotNull] MmlParser.SpcContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.spcList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpcList([NotNull] MmlParser.SpcListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.spcList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpcList([NotNull] MmlParser.SpcListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPad([NotNull] MmlParser.PadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPad([NotNull] MmlParser.PadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] MmlParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] MmlParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.halvetempo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHalvetempo([NotNull] MmlParser.HalvetempoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.halvetempo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHalvetempo([NotNull] MmlParser.HalvetempoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OptionGroup</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionGroup([NotNull] MmlParser.OptionGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OptionGroup</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionGroup([NotNull] MmlParser.OptionGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleOption</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleOption([NotNull] MmlParser.SingleOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleOption</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleOption([NotNull] MmlParser.SingleOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.optionItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionItem([NotNull] MmlParser.OptionItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.optionItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionItem([NotNull] MmlParser.OptionItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>GeneralAmkVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneralAmkVersion([NotNull] MmlParser.GeneralAmkVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GeneralAmkVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneralAmkVersion([NotNull] MmlParser.GeneralAmkVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AmmVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmmVersion([NotNull] MmlParser.AmmVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AmmVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmmVersion([NotNull] MmlParser.AmmVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Am4Version</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAm4Version([NotNull] MmlParser.Am4VersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Am4Version</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAm4Version([NotNull] MmlParser.Am4VersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.amm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmm([NotNull] MmlParser.AmmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.amm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmm([NotNull] MmlParser.AmmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.am4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAm4([NotNull] MmlParser.Am4Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.am4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAm4([NotNull] MmlParser.Am4Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.amkVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmkVersion([NotNull] MmlParser.AmkVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.amkVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmkVersion([NotNull] MmlParser.AmkVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.soundChannel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSoundChannel([NotNull] MmlParser.SoundChannelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.soundChannel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSoundChannel([NotNull] MmlParser.SoundChannelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.introEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntroEnd([NotNull] MmlParser.IntroEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.introEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntroEnd([NotNull] MmlParser.IntroEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.channelContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChannelContents([NotNull] MmlParser.ChannelContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.channelContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChannelContents([NotNull] MmlParser.ChannelContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.atomics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomics([NotNull] MmlParser.AtomicsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.atomics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomics([NotNull] MmlParser.AtomicsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.note"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNote([NotNull] MmlParser.NoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.note"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNote([NotNull] MmlParser.NoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.rest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRest([NotNull] MmlParser.RestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.rest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRest([NotNull] MmlParser.RestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.octave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOctave([NotNull] MmlParser.OctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.octave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOctave([NotNull] MmlParser.OctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.lowerOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLowerOctave([NotNull] MmlParser.LowerOctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.lowerOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLowerOctave([NotNull] MmlParser.LowerOctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.raiseOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaiseOctave([NotNull] MmlParser.RaiseOctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.raiseOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaiseOctave([NotNull] MmlParser.RaiseOctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.noiseNote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoiseNote([NotNull] MmlParser.NoiseNoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.noiseNote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoiseNote([NotNull] MmlParser.NoiseNoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Volume</c>
	/// labeled alternative in <see cref="MmlParser.volumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVolume([NotNull] MmlParser.VolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Volume</c>
	/// labeled alternative in <see cref="MmlParser.volumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVolume([NotNull] MmlParser.VolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexVolume</c>
	/// labeled alternative in <see cref="MmlParser.volumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexVolume([NotNull] MmlParser.HexVolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexVolume</c>
	/// labeled alternative in <see cref="MmlParser.volumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexVolume([NotNull] MmlParser.HexVolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Tune</c>
	/// labeled alternative in <see cref="MmlParser.tuneCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTune([NotNull] MmlParser.TuneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Tune</c>
	/// labeled alternative in <see cref="MmlParser.tuneCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTune([NotNull] MmlParser.TuneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexTune</c>
	/// labeled alternative in <see cref="MmlParser.tuneCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexTune([NotNull] MmlParser.HexTuneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexTune</c>
	/// labeled alternative in <see cref="MmlParser.tuneCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexTune([NotNull] MmlParser.HexTuneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.quantization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantization([NotNull] MmlParser.QuantizationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.quantization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantization([NotNull] MmlParser.QuantizationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Pan</c>
	/// labeled alternative in <see cref="MmlParser.panCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPan([NotNull] MmlParser.PanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Pan</c>
	/// labeled alternative in <see cref="MmlParser.panCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPan([NotNull] MmlParser.PanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexPan</c>
	/// labeled alternative in <see cref="MmlParser.panCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexPan([NotNull] MmlParser.HexPanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexPan</c>
	/// labeled alternative in <see cref="MmlParser.panCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexPan([NotNull] MmlParser.HexPanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Vibrato</c>
	/// labeled alternative in <see cref="MmlParser.vibratoCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVibrato([NotNull] MmlParser.VibratoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Vibrato</c>
	/// labeled alternative in <see cref="MmlParser.vibratoCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVibrato([NotNull] MmlParser.VibratoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexVibrato</c>
	/// labeled alternative in <see cref="MmlParser.vibratoCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexVibrato([NotNull] MmlParser.HexVibratoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexVibrato</c>
	/// labeled alternative in <see cref="MmlParser.vibratoCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexVibrato([NotNull] MmlParser.HexVibratoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pitchslide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPitchslide([NotNull] MmlParser.PitchslideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pitchslide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPitchslide([NotNull] MmlParser.PitchslideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.triplet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriplet([NotNull] MmlParser.TripletContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.triplet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriplet([NotNull] MmlParser.TripletContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.defaultLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultLength([NotNull] MmlParser.DefaultLengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.defaultLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultLength([NotNull] MmlParser.DefaultLengthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>GlobalVolume</c>
	/// labeled alternative in <see cref="MmlParser.globalVolumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalVolume([NotNull] MmlParser.GlobalVolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GlobalVolume</c>
	/// labeled alternative in <see cref="MmlParser.globalVolumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalVolume([NotNull] MmlParser.GlobalVolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexGlobalVolume</c>
	/// labeled alternative in <see cref="MmlParser.globalVolumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexGlobalVolume([NotNull] MmlParser.HexGlobalVolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexGlobalVolume</c>
	/// labeled alternative in <see cref="MmlParser.globalVolumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexGlobalVolume([NotNull] MmlParser.HexGlobalVolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Tempo</c>
	/// labeled alternative in <see cref="MmlParser.tempoCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTempo([NotNull] MmlParser.TempoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Tempo</c>
	/// labeled alternative in <see cref="MmlParser.tempoCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTempo([NotNull] MmlParser.TempoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexTempo</c>
	/// labeled alternative in <see cref="MmlParser.tempoCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexTempo([NotNull] MmlParser.HexTempoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexTempo</c>
	/// labeled alternative in <see cref="MmlParser.tempoCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexTempo([NotNull] MmlParser.HexTempoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Instrument</c>
	/// labeled alternative in <see cref="MmlParser.instrumentCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstrument([NotNull] MmlParser.InstrumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Instrument</c>
	/// labeled alternative in <see cref="MmlParser.instrumentCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstrument([NotNull] MmlParser.InstrumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexInstrument</c>
	/// labeled alternative in <see cref="MmlParser.instrumentCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexInstrument([NotNull] MmlParser.HexInstrumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexInstrument</c>
	/// labeled alternative in <see cref="MmlParser.instrumentCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexInstrument([NotNull] MmlParser.HexInstrumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.nakedTie"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNakedTie([NotNull] MmlParser.NakedTieContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.nakedTie"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNakedTie([NotNull] MmlParser.NakedTieContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.qmark"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQmark([NotNull] MmlParser.QmarkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.qmark"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQmark([NotNull] MmlParser.QmarkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pipe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPipe([NotNull] MmlParser.PipeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pipe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPipe([NotNull] MmlParser.PipeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.loopers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopers([NotNull] MmlParser.LoopersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.loopers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopers([NotNull] MmlParser.LoopersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.logicControls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicControls([NotNull] MmlParser.LogicControlsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.logicControls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicControls([NotNull] MmlParser.LogicControlsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.logicCalls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicCalls([NotNull] MmlParser.LogicCallsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.logicCalls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicCalls([NotNull] MmlParser.LogicCallsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteLogicCalls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoteLogicCalls([NotNull] MmlParser.RemoteLogicCallsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteLogicCalls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoteLogicCalls([NotNull] MmlParser.RemoteLogicCallsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.superLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperLoop([NotNull] MmlParser.SuperLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.superLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperLoop([NotNull] MmlParser.SuperLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.superLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperLoopContents([NotNull] MmlParser.SuperLoopContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.superLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperLoopContents([NotNull] MmlParser.SuperLoopContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.simpleLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleLoop([NotNull] MmlParser.SimpleLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.simpleLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleLoop([NotNull] MmlParser.SimpleLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.simpleLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleLoopContents([NotNull] MmlParser.SimpleLoopContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.simpleLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleLoopContents([NotNull] MmlParser.SimpleLoopContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSuperLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalSuperLoop([NotNull] MmlParser.TerminalSuperLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSuperLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalSuperLoop([NotNull] MmlParser.TerminalSuperLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSuperLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalSuperLoopContents([NotNull] MmlParser.TerminalSuperLoopContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSuperLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalSuperLoopContents([NotNull] MmlParser.TerminalSuperLoopContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSimpleLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalSimpleLoop([NotNull] MmlParser.TerminalSimpleLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSimpleLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalSimpleLoop([NotNull] MmlParser.TerminalSimpleLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSimpleLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalSimpleLoopContents([NotNull] MmlParser.TerminalSimpleLoopContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSimpleLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalSimpleLoopContents([NotNull] MmlParser.TerminalSimpleLoopContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoteCode([NotNull] MmlParser.RemoteCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoteCode([NotNull] MmlParser.RemoteCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteCodeContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoteCodeContents([NotNull] MmlParser.RemoteCodeContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteCodeContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoteCodeContents([NotNull] MmlParser.RemoteCodeContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallLoop([NotNull] MmlParser.CallLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallLoop([NotNull] MmlParser.CallLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callRemoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallRemoteCode([NotNull] MmlParser.CallRemoteCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callRemoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallRemoteCode([NotNull] MmlParser.CallRemoteCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.stopRemoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStopRemoteCode([NotNull] MmlParser.StopRemoteCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.stopRemoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStopRemoteCode([NotNull] MmlParser.StopRemoteCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callPreviousLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallPreviousLoop([NotNull] MmlParser.CallPreviousLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callPreviousLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallPreviousLoop([NotNull] MmlParser.CallPreviousLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.noloopCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoloopCommand([NotNull] MmlParser.NoloopCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.noloopCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoloopCommand([NotNull] MmlParser.NoloopCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SampleLoad</c>
	/// labeled alternative in <see cref="MmlParser.sampleLoadCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSampleLoad([NotNull] MmlParser.SampleLoadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SampleLoad</c>
	/// labeled alternative in <see cref="MmlParser.sampleLoadCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSampleLoad([NotNull] MmlParser.SampleLoadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>HexSampleLoad</c>
	/// labeled alternative in <see cref="MmlParser.sampleLoadCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexSampleLoad([NotNull] MmlParser.HexSampleLoadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>HexSampleLoad</c>
	/// labeled alternative in <see cref="MmlParser.sampleLoadCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexSampleLoad([NotNull] MmlParser.HexSampleLoadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.replacements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplacements([NotNull] MmlParser.ReplacementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.replacements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplacements([NotNull] MmlParser.ReplacementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.globalHexCommands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalHexCommands([NotNull] MmlParser.GlobalHexCommandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.globalHexCommands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalHexCommands([NotNull] MmlParser.GlobalHexCommandsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.channelHexCommands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChannelHexCommands([NotNull] MmlParser.ChannelHexCommandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.channelHexCommands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChannelHexCommands([NotNull] MmlParser.ChannelHexCommandsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.daInstrument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDaInstrument([NotNull] MmlParser.DaInstrumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.daInstrument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDaInstrument([NotNull] MmlParser.DaInstrumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.dbPan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDbPan([NotNull] MmlParser.DbPanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.dbPan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDbPan([NotNull] MmlParser.DbPanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.dcPanFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDcPanFade([NotNull] MmlParser.DcPanFadeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.dcPanFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDcPanFade([NotNull] MmlParser.DcPanFadeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.ddPitchBlendCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDdPitchBlendCommand([NotNull] MmlParser.DdPitchBlendCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.ddPitchBlendCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDdPitchBlendCommand([NotNull] MmlParser.DdPitchBlendCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.ddPitchBlendItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDdPitchBlendItems([NotNull] MmlParser.DdPitchBlendItemsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.ddPitchBlendItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDdPitchBlendItems([NotNull] MmlParser.DdPitchBlendItemsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.deVibratoStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeVibratoStart([NotNull] MmlParser.DeVibratoStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.deVibratoStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeVibratoStart([NotNull] MmlParser.DeVibratoStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.eaVibratoFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEaVibratoFade([NotNull] MmlParser.EaVibratoFadeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.eaVibratoFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEaVibratoFade([NotNull] MmlParser.EaVibratoFadeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.dfVibratoEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDfVibratoEnd([NotNull] MmlParser.DfVibratoEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.dfVibratoEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDfVibratoEnd([NotNull] MmlParser.DfVibratoEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e0GlobalVolume"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE0GlobalVolume([NotNull] MmlParser.E0GlobalVolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e0GlobalVolume"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE0GlobalVolume([NotNull] MmlParser.E0GlobalVolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e1GlobalVolumeFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE1GlobalVolumeFade([NotNull] MmlParser.E1GlobalVolumeFadeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e1GlobalVolumeFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE1GlobalVolumeFade([NotNull] MmlParser.E1GlobalVolumeFadeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e2Tempo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE2Tempo([NotNull] MmlParser.E2TempoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e2Tempo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE2Tempo([NotNull] MmlParser.E2TempoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e3TempoFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE3TempoFade([NotNull] MmlParser.E3TempoFadeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e3TempoFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE3TempoFade([NotNull] MmlParser.E3TempoFadeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e4GlobalTranspose"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE4GlobalTranspose([NotNull] MmlParser.E4GlobalTransposeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e4GlobalTranspose"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE4GlobalTranspose([NotNull] MmlParser.E4GlobalTransposeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e5Tremolo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE5Tremolo([NotNull] MmlParser.E5TremoloContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e5Tremolo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE5Tremolo([NotNull] MmlParser.E5TremoloContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e6SubloopStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE6SubloopStart([NotNull] MmlParser.E6SubloopStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e6SubloopStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE6SubloopStart([NotNull] MmlParser.E6SubloopStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e6SubloopEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE6SubloopEnd([NotNull] MmlParser.E6SubloopEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e6SubloopEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE6SubloopEnd([NotNull] MmlParser.E6SubloopEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e7Volume"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE7Volume([NotNull] MmlParser.E7VolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e7Volume"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE7Volume([NotNull] MmlParser.E7VolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.e8VolumeFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE8VolumeFade([NotNull] MmlParser.E8VolumeFadeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.e8VolumeFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE8VolumeFade([NotNull] MmlParser.E8VolumeFadeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.ebPitchEnvelopeRelease"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEbPitchEnvelopeRelease([NotNull] MmlParser.EbPitchEnvelopeReleaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.ebPitchEnvelopeRelease"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEbPitchEnvelopeRelease([NotNull] MmlParser.EbPitchEnvelopeReleaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.ecPitchEnvelopeAttack"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEcPitchEnvelopeAttack([NotNull] MmlParser.EcPitchEnvelopeAttackContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.ecPitchEnvelopeAttack"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEcPitchEnvelopeAttack([NotNull] MmlParser.EcPitchEnvelopeAttackContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EDCustomGAIN</c>
	/// labeled alternative in <see cref="MmlParser.edCustomADSROrGain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEDCustomGAIN([NotNull] MmlParser.EDCustomGAINContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EDCustomGAIN</c>
	/// labeled alternative in <see cref="MmlParser.edCustomADSROrGain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEDCustomGAIN([NotNull] MmlParser.EDCustomGAINContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EDCustomASDR</c>
	/// labeled alternative in <see cref="MmlParser.edCustomADSROrGain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEDCustomASDR([NotNull] MmlParser.EDCustomASDRContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EDCustomASDR</c>
	/// labeled alternative in <see cref="MmlParser.edCustomADSROrGain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEDCustomASDR([NotNull] MmlParser.EDCustomASDRContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.eeTuneChannel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEeTuneChannel([NotNull] MmlParser.EeTuneChannelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.eeTuneChannel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEeTuneChannel([NotNull] MmlParser.EeTuneChannelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.efEcho1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEfEcho1([NotNull] MmlParser.EfEcho1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.efEcho1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEfEcho1([NotNull] MmlParser.EfEcho1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.f0EchoOff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF0EchoOff([NotNull] MmlParser.F0EchoOffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.f0EchoOff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF0EchoOff([NotNull] MmlParser.F0EchoOffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.f1Echo2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF1Echo2([NotNull] MmlParser.F1Echo2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.f1Echo2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF1Echo2([NotNull] MmlParser.F1Echo2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.f2EchoFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF2EchoFade([NotNull] MmlParser.F2EchoFadeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.f2EchoFade"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF2EchoFade([NotNull] MmlParser.F2EchoFadeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.f3SampleLoad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF3SampleLoad([NotNull] MmlParser.F3SampleLoadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.f3SampleLoad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF3SampleLoad([NotNull] MmlParser.F3SampleLoadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4EnableYoshiDrumsChannel5</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4EnableYoshiDrumsChannel5([NotNull] MmlParser.F4EnableYoshiDrumsChannel5Context context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4EnableYoshiDrumsChannel5</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4EnableYoshiDrumsChannel5([NotNull] MmlParser.F4EnableYoshiDrumsChannel5Context context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4ToggleLegato</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4ToggleLegato([NotNull] MmlParser.F4ToggleLegatoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4ToggleLegato</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4ToggleLegato([NotNull] MmlParser.F4ToggleLegatoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4LightStaccato</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4LightStaccato([NotNull] MmlParser.F4LightStaccatoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4LightStaccato</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4LightStaccato([NotNull] MmlParser.F4LightStaccatoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4SNESSync</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4SNESSync([NotNull] MmlParser.F4SNESSyncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4SNESSync</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4SNESSync([NotNull] MmlParser.F4SNESSyncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4EnableYoshiDrums</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4EnableYoshiDrums([NotNull] MmlParser.F4EnableYoshiDrumsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4EnableYoshiDrums</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4EnableYoshiDrums([NotNull] MmlParser.F4EnableYoshiDrumsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4TempoHikeOff</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4TempoHikeOff([NotNull] MmlParser.F4TempoHikeOffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4TempoHikeOff</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4TempoHikeOff([NotNull] MmlParser.F4TempoHikeOffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4NSPCVelocityTable</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4NSPCVelocityTable([NotNull] MmlParser.F4NSPCVelocityTableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4NSPCVelocityTable</c>
	/// labeled alternative in <see cref="MmlParser.f4GlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4NSPCVelocityTable([NotNull] MmlParser.F4NSPCVelocityTableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4EchoToggle</c>
	/// labeled alternative in <see cref="MmlParser.f4ChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4EchoToggle([NotNull] MmlParser.F4EchoToggleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4EchoToggle</c>
	/// labeled alternative in <see cref="MmlParser.f4ChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4EchoToggle([NotNull] MmlParser.F4EchoToggleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>F4RestoreInstrument</c>
	/// labeled alternative in <see cref="MmlParser.f4ChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF4RestoreInstrument([NotNull] MmlParser.F4RestoreInstrumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>F4RestoreInstrument</c>
	/// labeled alternative in <see cref="MmlParser.f4ChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF4RestoreInstrument([NotNull] MmlParser.F4RestoreInstrumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.f5FIRFilter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF5FIRFilter([NotNull] MmlParser.F5FIRFilterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.f5FIRFilter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF5FIRFilter([NotNull] MmlParser.F5FIRFilterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.f6DSPWrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF6DSPWrite([NotNull] MmlParser.F6DSPWriteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.f6DSPWrite"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF6DSPWrite([NotNull] MmlParser.F6DSPWriteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.f8EnableNoise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF8EnableNoise([NotNull] MmlParser.F8EnableNoiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.f8EnableNoise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF8EnableNoise([NotNull] MmlParser.F8EnableNoiseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.f9DataSend"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF9DataSend([NotNull] MmlParser.F9DataSendContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.f9DataSend"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF9DataSend([NotNull] MmlParser.F9DataSendContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FAPitchModulation</c>
	/// labeled alternative in <see cref="MmlParser.faChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFAPitchModulation([NotNull] MmlParser.FAPitchModulationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FAPitchModulation</c>
	/// labeled alternative in <see cref="MmlParser.faChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFAPitchModulation([NotNull] MmlParser.FAPitchModulationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FACurrentChannelGain</c>
	/// labeled alternative in <see cref="MmlParser.faChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFACurrentChannelGain([NotNull] MmlParser.FACurrentChannelGainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FACurrentChannelGain</c>
	/// labeled alternative in <see cref="MmlParser.faChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFACurrentChannelGain([NotNull] MmlParser.FACurrentChannelGainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FASemitoneTune</c>
	/// labeled alternative in <see cref="MmlParser.faChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFASemitoneTune([NotNull] MmlParser.FASemitoneTuneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FASemitoneTune</c>
	/// labeled alternative in <see cref="MmlParser.faChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFASemitoneTune([NotNull] MmlParser.FASemitoneTuneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FAAmplify</c>
	/// labeled alternative in <see cref="MmlParser.faChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFAAmplify([NotNull] MmlParser.FAAmplifyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FAAmplify</c>
	/// labeled alternative in <see cref="MmlParser.faChannelItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFAAmplify([NotNull] MmlParser.FAAmplifyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FAEchoBufferReserve</c>
	/// labeled alternative in <see cref="MmlParser.faGlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFAEchoBufferReserve([NotNull] MmlParser.FAEchoBufferReserveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FAEchoBufferReserve</c>
	/// labeled alternative in <see cref="MmlParser.faGlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFAEchoBufferReserve([NotNull] MmlParser.FAEchoBufferReserveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FAHotPatchPreset</c>
	/// labeled alternative in <see cref="MmlParser.faGlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFAHotPatchPreset([NotNull] MmlParser.FAHotPatchPresetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FAHotPatchPreset</c>
	/// labeled alternative in <see cref="MmlParser.faGlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFAHotPatchPreset([NotNull] MmlParser.FAHotPatchPresetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FAHotPatchToggleBits</c>
	/// labeled alternative in <see cref="MmlParser.faGlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFAHotPatchToggleBits([NotNull] MmlParser.FAHotPatchToggleBitsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FAHotPatchToggleBits</c>
	/// labeled alternative in <see cref="MmlParser.faGlobalItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFAHotPatchToggleBits([NotNull] MmlParser.FAHotPatchToggleBitsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FBTrill</c>
	/// labeled alternative in <see cref="MmlParser.fbItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFBTrill([NotNull] MmlParser.FBTrillContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FBTrill</c>
	/// labeled alternative in <see cref="MmlParser.fbItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFBTrill([NotNull] MmlParser.FBTrillContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FBGlissando</c>
	/// labeled alternative in <see cref="MmlParser.fbItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFBGlissando([NotNull] MmlParser.FBGlissandoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FBGlissando</c>
	/// labeled alternative in <see cref="MmlParser.fbItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFBGlissando([NotNull] MmlParser.FBGlissandoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FBEnableArgeggio</c>
	/// labeled alternative in <see cref="MmlParser.fbItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFBEnableArgeggio([NotNull] MmlParser.FBEnableArgeggioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FBEnableArgeggio</c>
	/// labeled alternative in <see cref="MmlParser.fbItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFBEnableArgeggio([NotNull] MmlParser.FBEnableArgeggioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FCHexRemoteGain</c>
	/// labeled alternative in <see cref="MmlParser.fcItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFCHexRemoteGain([NotNull] MmlParser.FCHexRemoteGainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FCHexRemoteGain</c>
	/// labeled alternative in <see cref="MmlParser.fcItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFCHexRemoteGain([NotNull] MmlParser.FCHexRemoteGainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FCHexRemoteCommand</c>
	/// labeled alternative in <see cref="MmlParser.fcItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFCHexRemoteCommand([NotNull] MmlParser.FCHexRemoteCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FCHexRemoteCommand</c>
	/// labeled alternative in <see cref="MmlParser.fcItems"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFCHexRemoteCommand([NotNull] MmlParser.FCHexRemoteCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.fdTremoloOff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFdTremoloOff([NotNull] MmlParser.FdTremoloOffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.fdTremoloOff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFdTremoloOff([NotNull] MmlParser.FdTremoloOffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.fePitchEnvelopeOff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFePitchEnvelopeOff([NotNull] MmlParser.FePitchEnvelopeOffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.fePitchEnvelopeOff"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFePitchEnvelopeOff([NotNull] MmlParser.FePitchEnvelopeOffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.hexNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexNumber([NotNull] MmlParser.HexNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.hexNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexNumber([NotNull] MmlParser.HexNumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
