//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Projects/Visual Studio/Addmusic2/Addmusic2/Addmusic2/Mml.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMmlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MmlBaseListener : IMmlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.song"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSong([NotNull] MmlParser.SongContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.song"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSong([NotNull] MmlParser.SongContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.songElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSongElement([NotNull] MmlParser.SongElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.songElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSongElement([NotNull] MmlParser.SongElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.specialDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialDirective([NotNull] MmlParser.SpecialDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.specialDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialDirective([NotNull] MmlParser.SpecialDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.samples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSamples([NotNull] MmlParser.SamplesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.samples"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSamples([NotNull] MmlParser.SamplesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.samplesList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSamplesList([NotNull] MmlParser.SamplesListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.samplesList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSamplesList([NotNull] MmlParser.SamplesListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.instruments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruments([NotNull] MmlParser.InstrumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.instruments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruments([NotNull] MmlParser.InstrumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NamedInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedInstrumentListItem([NotNull] MmlParser.NamedInstrumentListItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedInstrumentListItem([NotNull] MmlParser.NamedInstrumentListItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>InstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstrumentListItem([NotNull] MmlParser.InstrumentListItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>InstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstrumentListItem([NotNull] MmlParser.InstrumentListItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NoiseInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoiseInstrumentListItem([NotNull] MmlParser.NoiseInstrumentListItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NoiseInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoiseInstrumentListItem([NotNull] MmlParser.NoiseInstrumentListItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.spc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpc([NotNull] MmlParser.SpcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.spc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpc([NotNull] MmlParser.SpcContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.spcList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpcList([NotNull] MmlParser.SpcListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.spcList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpcList([NotNull] MmlParser.SpcListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPad([NotNull] MmlParser.PadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPad([NotNull] MmlParser.PadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] MmlParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] MmlParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.halvetempo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHalvetempo([NotNull] MmlParser.HalvetempoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.halvetempo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHalvetempo([NotNull] MmlParser.HalvetempoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OptionGroup</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionGroup([NotNull] MmlParser.OptionGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OptionGroup</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionGroup([NotNull] MmlParser.OptionGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleOption</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleOption([NotNull] MmlParser.SingleOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleOption</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleOption([NotNull] MmlParser.SingleOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.optionItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionItem([NotNull] MmlParser.OptionItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.optionItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionItem([NotNull] MmlParser.OptionItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>GeneralAmkVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneralAmkVersion([NotNull] MmlParser.GeneralAmkVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GeneralAmkVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneralAmkVersion([NotNull] MmlParser.GeneralAmkVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AmmVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmmVersion([NotNull] MmlParser.AmmVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AmmVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmmVersion([NotNull] MmlParser.AmmVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Am4Version</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAm4Version([NotNull] MmlParser.Am4VersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Am4Version</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAm4Version([NotNull] MmlParser.Am4VersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.amm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmm([NotNull] MmlParser.AmmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.amm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmm([NotNull] MmlParser.AmmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.am4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAm4([NotNull] MmlParser.Am4Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.am4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAm4([NotNull] MmlParser.Am4Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.amkVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmkVersion([NotNull] MmlParser.AmkVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.amkVersion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmkVersion([NotNull] MmlParser.AmkVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.soundChannel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSoundChannel([NotNull] MmlParser.SoundChannelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.soundChannel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSoundChannel([NotNull] MmlParser.SoundChannelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.introEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntroEnd([NotNull] MmlParser.IntroEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.introEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntroEnd([NotNull] MmlParser.IntroEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.channelContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChannelContents([NotNull] MmlParser.ChannelContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.channelContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChannelContents([NotNull] MmlParser.ChannelContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.atomics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomics([NotNull] MmlParser.AtomicsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.atomics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomics([NotNull] MmlParser.AtomicsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.note"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNote([NotNull] MmlParser.NoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.note"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNote([NotNull] MmlParser.NoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.rest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRest([NotNull] MmlParser.RestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.rest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRest([NotNull] MmlParser.RestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.octave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOctave([NotNull] MmlParser.OctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.octave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOctave([NotNull] MmlParser.OctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.lowerOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLowerOctave([NotNull] MmlParser.LowerOctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.lowerOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLowerOctave([NotNull] MmlParser.LowerOctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.raiseOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaiseOctave([NotNull] MmlParser.RaiseOctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.raiseOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaiseOctave([NotNull] MmlParser.RaiseOctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.noiseNote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoiseNote([NotNull] MmlParser.NoiseNoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.noiseNote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoiseNote([NotNull] MmlParser.NoiseNoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.volume"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVolume([NotNull] MmlParser.VolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.volume"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVolume([NotNull] MmlParser.VolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.tune"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTune([NotNull] MmlParser.TuneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.tune"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTune([NotNull] MmlParser.TuneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.quantization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantization([NotNull] MmlParser.QuantizationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.quantization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantization([NotNull] MmlParser.QuantizationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPan([NotNull] MmlParser.PanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPan([NotNull] MmlParser.PanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.vibrato"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVibrato([NotNull] MmlParser.VibratoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.vibrato"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVibrato([NotNull] MmlParser.VibratoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pitchslide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPitchslide([NotNull] MmlParser.PitchslideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pitchslide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPitchslide([NotNull] MmlParser.PitchslideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.triplet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriplet([NotNull] MmlParser.TripletContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.triplet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriplet([NotNull] MmlParser.TripletContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.defaultLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultLength([NotNull] MmlParser.DefaultLengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.defaultLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultLength([NotNull] MmlParser.DefaultLengthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.globalVolume"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalVolume([NotNull] MmlParser.GlobalVolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.globalVolume"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalVolume([NotNull] MmlParser.GlobalVolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.tempo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTempo([NotNull] MmlParser.TempoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.tempo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTempo([NotNull] MmlParser.TempoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.instrument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstrument([NotNull] MmlParser.InstrumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.instrument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstrument([NotNull] MmlParser.InstrumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.nakedTie"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNakedTie([NotNull] MmlParser.NakedTieContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.nakedTie"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNakedTie([NotNull] MmlParser.NakedTieContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.qmark"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQmark([NotNull] MmlParser.QmarkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.qmark"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQmark([NotNull] MmlParser.QmarkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.loopers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopers([NotNull] MmlParser.LoopersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.loopers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopers([NotNull] MmlParser.LoopersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.logicControls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicControls([NotNull] MmlParser.LogicControlsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.logicControls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicControls([NotNull] MmlParser.LogicControlsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.logicCalls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicCalls([NotNull] MmlParser.LogicCallsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.logicCalls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicCalls([NotNull] MmlParser.LogicCallsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteLogicCalls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoteLogicCalls([NotNull] MmlParser.RemoteLogicCallsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteLogicCalls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoteLogicCalls([NotNull] MmlParser.RemoteLogicCallsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.superLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperLoop([NotNull] MmlParser.SuperLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.superLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperLoop([NotNull] MmlParser.SuperLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.superLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperLoopContents([NotNull] MmlParser.SuperLoopContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.superLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperLoopContents([NotNull] MmlParser.SuperLoopContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.simpleLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleLoop([NotNull] MmlParser.SimpleLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.simpleLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleLoop([NotNull] MmlParser.SimpleLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.simpleLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleLoopContents([NotNull] MmlParser.SimpleLoopContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.simpleLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleLoopContents([NotNull] MmlParser.SimpleLoopContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSuperLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalSuperLoop([NotNull] MmlParser.TerminalSuperLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSuperLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalSuperLoop([NotNull] MmlParser.TerminalSuperLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSuperLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalSuperLoopContents([NotNull] MmlParser.TerminalSuperLoopContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSuperLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalSuperLoopContents([NotNull] MmlParser.TerminalSuperLoopContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSimpleLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalSimpleLoop([NotNull] MmlParser.TerminalSimpleLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSimpleLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalSimpleLoop([NotNull] MmlParser.TerminalSimpleLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSimpleLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalSimpleLoopContents([NotNull] MmlParser.TerminalSimpleLoopContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSimpleLoopContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalSimpleLoopContents([NotNull] MmlParser.TerminalSimpleLoopContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoteCode([NotNull] MmlParser.RemoteCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoteCode([NotNull] MmlParser.RemoteCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteCodeContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoteCodeContents([NotNull] MmlParser.RemoteCodeContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteCodeContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoteCodeContents([NotNull] MmlParser.RemoteCodeContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallLoop([NotNull] MmlParser.CallLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallLoop([NotNull] MmlParser.CallLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callRemoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallRemoteCode([NotNull] MmlParser.CallRemoteCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callRemoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallRemoteCode([NotNull] MmlParser.CallRemoteCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.stopRemoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStopRemoteCode([NotNull] MmlParser.StopRemoteCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.stopRemoteCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStopRemoteCode([NotNull] MmlParser.StopRemoteCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callPreviousLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallPreviousLoop([NotNull] MmlParser.CallPreviousLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callPreviousLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallPreviousLoop([NotNull] MmlParser.CallPreviousLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.noloopCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoloopCommand([NotNull] MmlParser.NoloopCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.noloopCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoloopCommand([NotNull] MmlParser.NoloopCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.sampleLoad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSampleLoad([NotNull] MmlParser.SampleLoadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.sampleLoad"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSampleLoad([NotNull] MmlParser.SampleLoadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.replacements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplacements([NotNull] MmlParser.ReplacementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.replacements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplacements([NotNull] MmlParser.ReplacementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.hexNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexNumber([NotNull] MmlParser.HexNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.hexNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexNumber([NotNull] MmlParser.HexNumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
