//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Projects/Visual Studio/Addmusic2/Addmusic2/Addmusic2/Mml.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MmlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMmlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.song"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSong([NotNull] MmlParser.SongContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.song"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSong([NotNull] MmlParser.SongContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.songElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSongElement([NotNull] MmlParser.SongElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.songElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSongElement([NotNull] MmlParser.SongElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.specialDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecialDirective([NotNull] MmlParser.SpecialDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.specialDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecialDirective([NotNull] MmlParser.SpecialDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.samples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSamples([NotNull] MmlParser.SamplesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.samples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSamples([NotNull] MmlParser.SamplesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.samplesList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSamplesList([NotNull] MmlParser.SamplesListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.samplesList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSamplesList([NotNull] MmlParser.SamplesListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.instruments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruments([NotNull] MmlParser.InstrumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.instruments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruments([NotNull] MmlParser.InstrumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.instrumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstrumentsList([NotNull] MmlParser.InstrumentsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.instrumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstrumentsList([NotNull] MmlParser.InstrumentsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.spc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpc([NotNull] MmlParser.SpcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.spc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpc([NotNull] MmlParser.SpcContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.spcList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpcList([NotNull] MmlParser.SpcListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.spcList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpcList([NotNull] MmlParser.SpcListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPad([NotNull] MmlParser.PadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPad([NotNull] MmlParser.PadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] MmlParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] MmlParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.halvetempo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHalvetempo([NotNull] MmlParser.HalvetempoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.halvetempo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHalvetempo([NotNull] MmlParser.HalvetempoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption([NotNull] MmlParser.OptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption([NotNull] MmlParser.OptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.optionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionItem([NotNull] MmlParser.OptionItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.optionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionItem([NotNull] MmlParser.OptionItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmk([NotNull] MmlParser.AmkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmk([NotNull] MmlParser.AmkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.amkVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmkVersion([NotNull] MmlParser.AmkVersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.amkVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmkVersion([NotNull] MmlParser.AmkVersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.soundChannel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoundChannel([NotNull] MmlParser.SoundChannelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.soundChannel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoundChannel([NotNull] MmlParser.SoundChannelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.introEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntroEnd([NotNull] MmlParser.IntroEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.introEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntroEnd([NotNull] MmlParser.IntroEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.channelContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChannelContents([NotNull] MmlParser.ChannelContentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.channelContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChannelContents([NotNull] MmlParser.ChannelContentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.atomics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomics([NotNull] MmlParser.AtomicsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.atomics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomics([NotNull] MmlParser.AtomicsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNote([NotNull] MmlParser.NoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNote([NotNull] MmlParser.NoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.rest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRest([NotNull] MmlParser.RestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.rest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRest([NotNull] MmlParser.RestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.octave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOctave([NotNull] MmlParser.OctaveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.octave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOctave([NotNull] MmlParser.OctaveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.lowerOctave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLowerOctave([NotNull] MmlParser.LowerOctaveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.lowerOctave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLowerOctave([NotNull] MmlParser.LowerOctaveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.raiseOctave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaiseOctave([NotNull] MmlParser.RaiseOctaveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.raiseOctave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaiseOctave([NotNull] MmlParser.RaiseOctaveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.noiseNote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoiseNote([NotNull] MmlParser.NoiseNoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.noiseNote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoiseNote([NotNull] MmlParser.NoiseNoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.volume"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVolume([NotNull] MmlParser.VolumeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.volume"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVolume([NotNull] MmlParser.VolumeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.tune"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTune([NotNull] MmlParser.TuneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.tune"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTune([NotNull] MmlParser.TuneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.quantization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantization([NotNull] MmlParser.QuantizationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.quantization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantization([NotNull] MmlParser.QuantizationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPan([NotNull] MmlParser.PanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPan([NotNull] MmlParser.PanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.vibrato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVibrato([NotNull] MmlParser.VibratoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.vibrato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVibrato([NotNull] MmlParser.VibratoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.pitchslide"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPitchslide([NotNull] MmlParser.PitchslideContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.pitchslide"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPitchslide([NotNull] MmlParser.PitchslideContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.triplet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriplet([NotNull] MmlParser.TripletContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.triplet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriplet([NotNull] MmlParser.TripletContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.defaultLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultLength([NotNull] MmlParser.DefaultLengthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.defaultLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultLength([NotNull] MmlParser.DefaultLengthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.globalVolume"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalVolume([NotNull] MmlParser.GlobalVolumeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.globalVolume"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalVolume([NotNull] MmlParser.GlobalVolumeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.tempo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTempo([NotNull] MmlParser.TempoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.tempo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTempo([NotNull] MmlParser.TempoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.instrument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstrument([NotNull] MmlParser.InstrumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.instrument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstrument([NotNull] MmlParser.InstrumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.nakedTie"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNakedTie([NotNull] MmlParser.NakedTieContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.nakedTie"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNakedTie([NotNull] MmlParser.NakedTieContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.loopers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopers([NotNull] MmlParser.LoopersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.loopers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopers([NotNull] MmlParser.LoopersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.logicControls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicControls([NotNull] MmlParser.LogicControlsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.logicControls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicControls([NotNull] MmlParser.LogicControlsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.logicCalls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicCalls([NotNull] MmlParser.LogicCallsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.logicCalls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicCalls([NotNull] MmlParser.LogicCallsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteLogicCalls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRemoteLogicCalls([NotNull] MmlParser.RemoteLogicCallsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteLogicCalls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRemoteLogicCalls([NotNull] MmlParser.RemoteLogicCallsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.superLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperLoop([NotNull] MmlParser.SuperLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.superLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperLoop([NotNull] MmlParser.SuperLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.simpleLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleLoop([NotNull] MmlParser.SimpleLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.simpleLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleLoop([NotNull] MmlParser.SimpleLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSuperLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminalSuperLoop([NotNull] MmlParser.TerminalSuperLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSuperLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminalSuperLoop([NotNull] MmlParser.TerminalSuperLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.terminalSimpleLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminalSimpleLoop([NotNull] MmlParser.TerminalSimpleLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.terminalSimpleLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminalSimpleLoop([NotNull] MmlParser.TerminalSimpleLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRemoteCode([NotNull] MmlParser.RemoteCodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRemoteCode([NotNull] MmlParser.RemoteCodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.remoteCodeContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRemoteCodeContents([NotNull] MmlParser.RemoteCodeContentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.remoteCodeContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRemoteCodeContents([NotNull] MmlParser.RemoteCodeContentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallLoop([NotNull] MmlParser.CallLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallLoop([NotNull] MmlParser.CallLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callRemoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallRemoteCode([NotNull] MmlParser.CallRemoteCodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callRemoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallRemoteCode([NotNull] MmlParser.CallRemoteCodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.stopRemoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStopRemoteCode([NotNull] MmlParser.StopRemoteCodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.stopRemoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStopRemoteCode([NotNull] MmlParser.StopRemoteCodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.callPreviousLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallPreviousLoop([NotNull] MmlParser.CallPreviousLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.callPreviousLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallPreviousLoop([NotNull] MmlParser.CallPreviousLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.noloopCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoloopCommand([NotNull] MmlParser.NoloopCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.noloopCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoloopCommand([NotNull] MmlParser.NoloopCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.sampleLoad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSampleLoad([NotNull] MmlParser.SampleLoadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.sampleLoad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSampleLoad([NotNull] MmlParser.SampleLoadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.replacements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReplacements([NotNull] MmlParser.ReplacementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.replacements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReplacements([NotNull] MmlParser.ReplacementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MmlParser.hexNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexNumber([NotNull] MmlParser.HexNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MmlParser.hexNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexNumber([NotNull] MmlParser.HexNumberContext context);
}
