//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Projects/Visual Studio/Addmusic2/Addmusic2/Addmusic2/Mml.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MmlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMmlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.song"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSong([NotNull] MmlParser.SongContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.songElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSongElement([NotNull] MmlParser.SongElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.specialDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialDirective([NotNull] MmlParser.SpecialDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.samples"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSamples([NotNull] MmlParser.SamplesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.samplesList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSamplesList([NotNull] MmlParser.SamplesListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.instruments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruments([NotNull] MmlParser.InstrumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamedInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedInstrumentListItem([NotNull] MmlParser.NamedInstrumentListItemContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrumentListItem([NotNull] MmlParser.InstrumentListItemContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NoiseInstrumentListItem</c>
	/// labeled alternative in <see cref="MmlParser.instrumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoiseInstrumentListItem([NotNull] MmlParser.NoiseInstrumentListItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.spc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpc([NotNull] MmlParser.SpcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.spcList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpcList([NotNull] MmlParser.SpcListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.pad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPad([NotNull] MmlParser.PadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath([NotNull] MmlParser.PathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.halvetempo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHalvetempo([NotNull] MmlParser.HalvetempoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OptionGroup</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionGroup([NotNull] MmlParser.OptionGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SingleOption</c>
	/// labeled alternative in <see cref="MmlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleOption([NotNull] MmlParser.SingleOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.optionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionItem([NotNull] MmlParser.OptionItemContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GeneralAmkVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneralAmkVersion([NotNull] MmlParser.GeneralAmkVersionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AmmVersion</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmmVersion([NotNull] MmlParser.AmmVersionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Am4Version</c>
	/// labeled alternative in <see cref="MmlParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAm4Version([NotNull] MmlParser.Am4VersionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.amm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmm([NotNull] MmlParser.AmmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.am4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAm4([NotNull] MmlParser.Am4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.amkVersion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmkVersion([NotNull] MmlParser.AmkVersionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.soundChannel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoundChannel([NotNull] MmlParser.SoundChannelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.introEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntroEnd([NotNull] MmlParser.IntroEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.channelContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChannelContents([NotNull] MmlParser.ChannelContentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.atomics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomics([NotNull] MmlParser.AtomicsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNote([NotNull] MmlParser.NoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.rest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRest([NotNull] MmlParser.RestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.octave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOctave([NotNull] MmlParser.OctaveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.lowerOctave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLowerOctave([NotNull] MmlParser.LowerOctaveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.raiseOctave"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaiseOctave([NotNull] MmlParser.RaiseOctaveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.noiseNote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoiseNote([NotNull] MmlParser.NoiseNoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.volume"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVolume([NotNull] MmlParser.VolumeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.tune"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTune([NotNull] MmlParser.TuneContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.quantization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantization([NotNull] MmlParser.QuantizationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.pan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPan([NotNull] MmlParser.PanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.vibrato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVibrato([NotNull] MmlParser.VibratoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.pitchslide"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPitchslide([NotNull] MmlParser.PitchslideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.triplet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriplet([NotNull] MmlParser.TripletContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.defaultLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultLength([NotNull] MmlParser.DefaultLengthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.globalVolume"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVolume([NotNull] MmlParser.GlobalVolumeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.tempo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTempo([NotNull] MmlParser.TempoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.instrument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstrument([NotNull] MmlParser.InstrumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.nakedTie"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNakedTie([NotNull] MmlParser.NakedTieContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.qmark"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQmark([NotNull] MmlParser.QmarkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.loopers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopers([NotNull] MmlParser.LoopersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.logicControls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicControls([NotNull] MmlParser.LogicControlsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.logicCalls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicCalls([NotNull] MmlParser.LogicCallsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.remoteLogicCalls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemoteLogicCalls([NotNull] MmlParser.RemoteLogicCallsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.superLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperLoop([NotNull] MmlParser.SuperLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.superLoopContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperLoopContents([NotNull] MmlParser.SuperLoopContentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.simpleLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleLoop([NotNull] MmlParser.SimpleLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.simpleLoopContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleLoopContents([NotNull] MmlParser.SimpleLoopContentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.terminalSuperLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalSuperLoop([NotNull] MmlParser.TerminalSuperLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.terminalSuperLoopContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalSuperLoopContents([NotNull] MmlParser.TerminalSuperLoopContentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.terminalSimpleLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalSimpleLoop([NotNull] MmlParser.TerminalSimpleLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.terminalSimpleLoopContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminalSimpleLoopContents([NotNull] MmlParser.TerminalSimpleLoopContentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.remoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemoteCode([NotNull] MmlParser.RemoteCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.remoteCodeContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemoteCodeContents([NotNull] MmlParser.RemoteCodeContentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.callLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallLoop([NotNull] MmlParser.CallLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.callRemoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallRemoteCode([NotNull] MmlParser.CallRemoteCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.stopRemoteCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStopRemoteCode([NotNull] MmlParser.StopRemoteCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.callPreviousLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallPreviousLoop([NotNull] MmlParser.CallPreviousLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.noloopCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoloopCommand([NotNull] MmlParser.NoloopCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.sampleLoad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSampleLoad([NotNull] MmlParser.SampleLoadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.replacements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReplacements([NotNull] MmlParser.ReplacementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MmlParser.hexNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexNumber([NotNull] MmlParser.HexNumberContext context);
}
