//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Projects/Visual Studio/Addmusic2/Addmusic2/Addmusic2/Preprocessor.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPreprocessorListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class PreprocessorBaseListener : IPreprocessorListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.song"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSong([NotNull] PreprocessorParser.SongContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.song"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSong([NotNull] PreprocessorParser.SongContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.preprocessorElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorElement([NotNull] PreprocessorParser.PreprocessorElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.preprocessorElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorElement([NotNull] PreprocessorParser.PreprocessorElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.replacements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplacements([NotNull] PreprocessorParser.ReplacementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.replacements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplacements([NotNull] PreprocessorParser.ReplacementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>GeneralAmkVersion</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneralAmkVersion([NotNull] PreprocessorParser.GeneralAmkVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GeneralAmkVersion</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneralAmkVersion([NotNull] PreprocessorParser.GeneralAmkVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AmmVersion</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmmVersion([NotNull] PreprocessorParser.AmmVersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AmmVersion</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmmVersion([NotNull] PreprocessorParser.AmmVersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Am4Version</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAm4Version([NotNull] PreprocessorParser.Am4VersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Am4Version</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAm4Version([NotNull] PreprocessorParser.Am4VersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AmkV1Version</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmkV1Version([NotNull] PreprocessorParser.AmkV1VersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AmkV1Version</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmkV1Version([NotNull] PreprocessorParser.AmkV1VersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.generalAmk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneralAmk([NotNull] PreprocessorParser.GeneralAmkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.generalAmk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneralAmk([NotNull] PreprocessorParser.GeneralAmkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.amm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmm([NotNull] PreprocessorParser.AmmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.amm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmm([NotNull] PreprocessorParser.AmmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.am4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAm4([NotNull] PreprocessorParser.Am4Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.am4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAm4([NotNull] PreprocessorParser.Am4Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.amkV1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmkV1([NotNull] PreprocessorParser.AmkV1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.amkV1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmkV1([NotNull] PreprocessorParser.AmkV1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.defines"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefines([NotNull] PreprocessorParser.DefinesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.defines"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefines([NotNull] PreprocessorParser.DefinesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefine([NotNull] PreprocessorParser.DefineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefine([NotNull] PreprocessorParser.DefineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.undefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUndefine([NotNull] PreprocessorParser.UndefineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.undefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUndefine([NotNull] PreprocessorParser.UndefineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.error"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterError([NotNull] PreprocessorParser.ErrorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.error"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitError([NotNull] PreprocessorParser.ErrorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.conditionalLogics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalLogics([NotNull] PreprocessorParser.ConditionalLogicsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.conditionalLogics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalLogics([NotNull] PreprocessorParser.ConditionalLogicsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleIfStatement</c>
	/// labeled alternative in <see cref="PreprocessorParser.if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleIfStatement([NotNull] PreprocessorParser.SingleIfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleIfStatement</c>
	/// labeled alternative in <see cref="PreprocessorParser.if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleIfStatement([NotNull] PreprocessorParser.SingleIfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStatementWithElseIfs</c>
	/// labeled alternative in <see cref="PreprocessorParser.if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatementWithElseIfs([NotNull] PreprocessorParser.IfStatementWithElseIfsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStatementWithElseIfs</c>
	/// labeled alternative in <see cref="PreprocessorParser.if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatementWithElseIfs([NotNull] PreprocessorParser.IfStatementWithElseIfsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.elseIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIf([NotNull] PreprocessorParser.ElseIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.elseIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIf([NotNull] PreprocessorParser.ElseIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse([NotNull] PreprocessorParser.ElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse([NotNull] PreprocessorParser.ElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.ifdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfdef([NotNull] PreprocessorParser.IfdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.ifdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfdef([NotNull] PreprocessorParser.IfdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.ifndef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfndef([NotNull] PreprocessorParser.IfndefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.ifndef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfndef([NotNull] PreprocessorParser.IfndefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreprocessorParser.arbitraryText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArbitraryText([NotNull] PreprocessorParser.ArbitraryTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreprocessorParser.arbitraryText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArbitraryText([NotNull] PreprocessorParser.ArbitraryTextContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
