//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Projects/Visual Studio/Addmusic2/Addmusic2/Addmusic2/Preprocessor.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PreprocessorParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPreprocessorVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.song"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSong([NotNull] PreprocessorParser.SongContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.preprocessorElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreprocessorElement([NotNull] PreprocessorParser.PreprocessorElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.replacements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReplacements([NotNull] PreprocessorParser.ReplacementsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GeneralAmkVersion</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneralAmkVersion([NotNull] PreprocessorParser.GeneralAmkVersionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AmmVersion</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmmVersion([NotNull] PreprocessorParser.AmmVersionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Am4Version</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAm4Version([NotNull] PreprocessorParser.Am4VersionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AmkV1Version</c>
	/// labeled alternative in <see cref="PreprocessorParser.amk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmkV1Version([NotNull] PreprocessorParser.AmkV1VersionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.generalAmk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneralAmk([NotNull] PreprocessorParser.GeneralAmkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.amm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmm([NotNull] PreprocessorParser.AmmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.am4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAm4([NotNull] PreprocessorParser.Am4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.amkV1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmkV1([NotNull] PreprocessorParser.AmkV1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.defines"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefines([NotNull] PreprocessorParser.DefinesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefine([NotNull] PreprocessorParser.DefineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.undefine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUndefine([NotNull] PreprocessorParser.UndefineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.error"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError([NotNull] PreprocessorParser.ErrorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.conditionalLogics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalLogics([NotNull] PreprocessorParser.ConditionalLogicsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SingleIfStatement</c>
	/// labeled alternative in <see cref="PreprocessorParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleIfStatement([NotNull] PreprocessorParser.SingleIfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStatementWithElseIfs</c>
	/// labeled alternative in <see cref="PreprocessorParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatementWithElseIfs([NotNull] PreprocessorParser.IfStatementWithElseIfsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.elseIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIf([NotNull] PreprocessorParser.ElseIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse([NotNull] PreprocessorParser.ElseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.ifdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfdef([NotNull] PreprocessorParser.IfdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.ifndef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfndef([NotNull] PreprocessorParser.IfndefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PreprocessorParser.arbitraryText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArbitraryText([NotNull] PreprocessorParser.ArbitraryTextContext context);
}
