//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Projects/Visual Studio/Addmusic2/Addmusic2/Addmusic2/Sfx.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISfxListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SfxBaseListener : ISfxListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.soundEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSoundEffect([NotNull] SfxParser.SoundEffectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.soundEffect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSoundEffect([NotNull] SfxParser.SoundEffectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.soundEffectElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSoundEffectElement([NotNull] SfxParser.SoundEffectElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.soundEffectElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSoundEffectElement([NotNull] SfxParser.SoundEffectElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.specialDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialDirective([NotNull] SfxParser.SpecialDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.specialDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialDirective([NotNull] SfxParser.SpecialDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.asm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsm([NotNull] SfxParser.AsmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.asm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsm([NotNull] SfxParser.AsmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.jsr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsr([NotNull] SfxParser.JsrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.jsr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsr([NotNull] SfxParser.JsrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.atomics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomics([NotNull] SfxParser.AtomicsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.atomics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomics([NotNull] SfxParser.AtomicsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.note"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNote([NotNull] SfxParser.NoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.note"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNote([NotNull] SfxParser.NoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.rest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRest([NotNull] SfxParser.RestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.rest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRest([NotNull] SfxParser.RestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.octave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOctave([NotNull] SfxParser.OctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.octave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOctave([NotNull] SfxParser.OctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.lowerOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLowerOctave([NotNull] SfxParser.LowerOctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.lowerOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLowerOctave([NotNull] SfxParser.LowerOctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.raiseOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaiseOctave([NotNull] SfxParser.RaiseOctaveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.raiseOctave"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaiseOctave([NotNull] SfxParser.RaiseOctaveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.pitchslide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPitchslide([NotNull] SfxParser.PitchslideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.pitchslide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPitchslide([NotNull] SfxParser.PitchslideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Volume</c>
	/// labeled alternative in <see cref="SfxParser.volumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVolume([NotNull] SfxParser.VolumeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Volume</c>
	/// labeled alternative in <see cref="SfxParser.volumeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVolume([NotNull] SfxParser.VolumeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.defaultLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultLength([NotNull] SfxParser.DefaultLengthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.defaultLength"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultLength([NotNull] SfxParser.DefaultLengthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Instrument</c>
	/// labeled alternative in <see cref="SfxParser.instrumentCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstrument([NotNull] SfxParser.InstrumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Instrument</c>
	/// labeled alternative in <see cref="SfxParser.instrumentCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstrument([NotNull] SfxParser.InstrumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.nakedTie"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNakedTie([NotNull] SfxParser.NakedTieContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.nakedTie"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNakedTie([NotNull] SfxParser.NakedTieContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.hexCommands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexCommands([NotNull] SfxParser.HexCommandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.hexCommands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexCommands([NotNull] SfxParser.HexCommandsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.e0SfxPriority"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE0SfxPriority([NotNull] SfxParser.E0SfxPriorityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.e0SfxPriority"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE0SfxPriority([NotNull] SfxParser.E0SfxPriorityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SfxParser.hexNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexNumber([NotNull] SfxParser.HexNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SfxParser.hexNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexNumber([NotNull] SfxParser.HexNumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
