//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Projects/Visual Studio/Addmusic2/Addmusic2/Addmusic2/Sfx.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class SfxParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		POUND=1, DOLLAR=2, COMMAT=3, AMPER=4, LBRACE=5, RBRACE=6, SHARP=7, FLAT=8, 
		DOT=9, TIE=10, GT=11, LT=12, COMMA=13, EQUAL=14, SEMICOLON=15, Note=16, 
		Rest=17, Octave=18, Volume=19, Tie=20, Instrument=21, Length=22, Asm=23, 
		Jsr=24, NDD=25, NE0=26, JsrIdentifier=27, AsmTextBlock=28, NUMBERS=29, 
		UNUMBERS=30, HexNumber=31, WHITESPACE=32, Comment=33;
	public const int
		RULE_soundEffect = 0, RULE_soundEffectElement = 1, RULE_specialDirective = 2, 
		RULE_asm = 3, RULE_jsr = 4, RULE_atomics = 5, RULE_note = 6, RULE_rest = 7, 
		RULE_octave = 8, RULE_lowerOctave = 9, RULE_raiseOctave = 10, RULE_pitchslide = 11, 
		RULE_volumeCommand = 12, RULE_defaultLength = 13, RULE_instrumentCommand = 14, 
		RULE_triplet = 15, RULE_nakedTie = 16, RULE_hexCommands = 17, RULE_ddPitchBlendCommand = 18, 
		RULE_ddPitchBlendItems = 19, RULE_e0SfxPriority = 20, RULE_hexNumber = 21;
	public static readonly string[] ruleNames = {
		"soundEffect", "soundEffectElement", "specialDirective", "asm", "jsr", 
		"atomics", "note", "rest", "octave", "lowerOctave", "raiseOctave", "pitchslide", 
		"volumeCommand", "defaultLength", "instrumentCommand", "triplet", "nakedTie", 
		"hexCommands", "ddPitchBlendCommand", "ddPitchBlendItems", "e0SfxPriority", 
		"hexNumber"
	};

	private static readonly string[] _LiteralNames = {
		null, "'#'", "'$'", "'@'", "'&'", "'{'", "'}'", "'+'", "'-'", "'.'", "'^'", 
		"'>'", "'<'", "','", "'='", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "POUND", "DOLLAR", "COMMAT", "AMPER", "LBRACE", "RBRACE", "SHARP", 
		"FLAT", "DOT", "TIE", "GT", "LT", "COMMA", "EQUAL", "SEMICOLON", "Note", 
		"Rest", "Octave", "Volume", "Tie", "Instrument", "Length", "Asm", "Jsr", 
		"NDD", "NE0", "JsrIdentifier", "AsmTextBlock", "NUMBERS", "UNUMBERS", 
		"HexNumber", "WHITESPACE", "Comment"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Sfx.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static SfxParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SfxParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SfxParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class SoundEffectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public E0SfxPriorityContext e0SfxPriority() {
			return GetRuleContext<E0SfxPriorityContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SoundEffectElementContext[] soundEffectElement() {
			return GetRuleContexts<SoundEffectElementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SoundEffectElementContext soundEffectElement(int i) {
			return GetRuleContext<SoundEffectElementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(SfxParser.Eof, 0); }
		public SoundEffectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_soundEffect; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterSoundEffect(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitSoundEffect(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSoundEffect(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SoundEffectContext soundEffect() {
		SoundEffectContext _localctx = new SoundEffectContext(Context, State);
		EnterRule(_localctx, 0, RULE_soundEffect);
		int _la;
		try {
			State = 53;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LBRACE:
			case GT:
			case LT:
			case Note:
			case Rest:
			case Octave:
			case Volume:
			case Tie:
			case Instrument:
			case Length:
			case Asm:
			case Jsr:
			case NDD:
			case NE0:
			case HexNumber:
				EnterOuterAlt(_localctx, 1);
				{
				State = 45;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==NE0) {
					{
					State = 44;
					e0SfxPriority();
					}
				}

				State = 48;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 47;
					soundEffectElement();
					}
					}
					State = 50;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 2214533152L) != 0) );
				}
				break;
			case Eof:
				EnterOuterAlt(_localctx, 2);
				{
				State = 52;
				Match(Eof);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SoundEffectElementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SpecialDirectiveContext specialDirective() {
			return GetRuleContext<SpecialDirectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AtomicsContext atomics() {
			return GetRuleContext<AtomicsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HexCommandsContext hexCommands() {
			return GetRuleContext<HexCommandsContext>(0);
		}
		public SoundEffectElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_soundEffectElement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterSoundEffectElement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitSoundEffectElement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSoundEffectElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SoundEffectElementContext soundEffectElement() {
		SoundEffectElementContext _localctx = new SoundEffectElementContext(Context, State);
		EnterRule(_localctx, 2, RULE_soundEffectElement);
		try {
			State = 58;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Asm:
			case Jsr:
				EnterOuterAlt(_localctx, 1);
				{
				State = 55;
				specialDirective();
				}
				break;
			case LBRACE:
			case GT:
			case LT:
			case Note:
			case Rest:
			case Octave:
			case Volume:
			case Tie:
			case Instrument:
			case Length:
				EnterOuterAlt(_localctx, 2);
				{
				State = 56;
				atomics();
				}
				break;
			case NDD:
			case HexNumber:
				EnterOuterAlt(_localctx, 3);
				{
				State = 57;
				hexCommands();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SpecialDirectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AsmContext asm() {
			return GetRuleContext<AsmContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public JsrContext jsr() {
			return GetRuleContext<JsrContext>(0);
		}
		public SpecialDirectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_specialDirective; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterSpecialDirective(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitSpecialDirective(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSpecialDirective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SpecialDirectiveContext specialDirective() {
		SpecialDirectiveContext _localctx = new SpecialDirectiveContext(Context, State);
		EnterRule(_localctx, 4, RULE_specialDirective);
		try {
			State = 62;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Asm:
				EnterOuterAlt(_localctx, 1);
				{
				State = 60;
				asm();
				}
				break;
			case Jsr:
				EnterOuterAlt(_localctx, 2);
				{
				State = 61;
				jsr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AsmContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Asm() { return GetToken(SfxParser.Asm, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode JsrIdentifier() { return GetToken(SfxParser.JsrIdentifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AsmTextBlock() { return GetToken(SfxParser.AsmTextBlock, 0); }
		public AsmContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_asm; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterAsm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitAsm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAsm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AsmContext asm() {
		AsmContext _localctx = new AsmContext(Context, State);
		EnterRule(_localctx, 6, RULE_asm);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			Match(Asm);
			State = 65;
			Match(JsrIdentifier);
			State = 66;
			Match(AsmTextBlock);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsrContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Jsr() { return GetToken(SfxParser.Jsr, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode JsrIdentifier() { return GetToken(SfxParser.JsrIdentifier, 0); }
		public JsrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterJsr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitJsr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsrContext jsr() {
		JsrContext _localctx = new JsrContext(Context, State);
		EnterRule(_localctx, 8, RULE_jsr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			Match(Jsr);
			State = 69;
			Match(JsrIdentifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtomicsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PitchslideContext pitchslide() {
			return GetRuleContext<PitchslideContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NoteContext note() {
			return GetRuleContext<NoteContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RestContext rest() {
			return GetRuleContext<RestContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OctaveContext octave() {
			return GetRuleContext<OctaveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LowerOctaveContext lowerOctave() {
			return GetRuleContext<LowerOctaveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RaiseOctaveContext raiseOctave() {
			return GetRuleContext<RaiseOctaveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VolumeCommandContext volumeCommand() {
			return GetRuleContext<VolumeCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DefaultLengthContext defaultLength() {
			return GetRuleContext<DefaultLengthContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstrumentCommandContext instrumentCommand() {
			return GetRuleContext<InstrumentCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NakedTieContext nakedTie() {
			return GetRuleContext<NakedTieContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TripletContext triplet() {
			return GetRuleContext<TripletContext>(0);
		}
		public AtomicsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atomics; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterAtomics(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitAtomics(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtomics(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomicsContext atomics() {
		AtomicsContext _localctx = new AtomicsContext(Context, State);
		EnterRule(_localctx, 10, RULE_atomics);
		try {
			State = 82;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 71;
				pitchslide();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 72;
				note();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 73;
				rest();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 74;
				octave();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 75;
				lowerOctave();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 76;
				raiseOctave();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 77;
				volumeCommand();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 78;
				defaultLength();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 79;
				instrumentCommand();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 80;
				nakedTie();
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 81;
				triplet();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NoteContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Note() { return GetToken(SfxParser.Note, 0); }
		public NoteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_note; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterNote(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitNote(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNote(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NoteContext note() {
		NoteContext _localctx = new NoteContext(Context, State);
		EnterRule(_localctx, 12, RULE_note);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			Match(Note);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RestContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Rest() { return GetToken(SfxParser.Rest, 0); }
		public RestContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rest; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterRest(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitRest(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRest(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RestContext rest() {
		RestContext _localctx = new RestContext(Context, State);
		EnterRule(_localctx, 14, RULE_rest);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			Match(Rest);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OctaveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Octave() { return GetToken(SfxParser.Octave, 0); }
		public OctaveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_octave; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterOctave(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitOctave(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOctave(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OctaveContext octave() {
		OctaveContext _localctx = new OctaveContext(Context, State);
		EnterRule(_localctx, 16, RULE_octave);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			Match(Octave);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LowerOctaveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(SfxParser.LT, 0); }
		public LowerOctaveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lowerOctave; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterLowerOctave(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitLowerOctave(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLowerOctave(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LowerOctaveContext lowerOctave() {
		LowerOctaveContext _localctx = new LowerOctaveContext(Context, State);
		EnterRule(_localctx, 18, RULE_lowerOctave);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90;
			Match(LT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RaiseOctaveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(SfxParser.GT, 0); }
		public RaiseOctaveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_raiseOctave; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterRaiseOctave(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitRaiseOctave(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRaiseOctave(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RaiseOctaveContext raiseOctave() {
		RaiseOctaveContext _localctx = new RaiseOctaveContext(Context, State);
		EnterRule(_localctx, 20, RULE_raiseOctave);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(GT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PitchslideContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Note() { return GetTokens(SfxParser.Note); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Note(int i) {
			return GetToken(SfxParser.Note, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Rest() { return GetTokens(SfxParser.Rest); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Rest(int i) {
			return GetToken(SfxParser.Rest, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AMPER() { return GetTokens(SfxParser.AMPER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AMPER(int i) {
			return GetToken(SfxParser.AMPER, i);
		}
		public PitchslideContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pitchslide; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterPitchslide(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitPitchslide(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPitchslide(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PitchslideContext pitchslide() {
		PitchslideContext _localctx = new PitchslideContext(Context, State);
		EnterRule(_localctx, 22, RULE_pitchslide);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94;
			_la = TokenStream.LA(1);
			if ( !(_la==Note || _la==Rest) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 95;
				Match(AMPER);
				State = 96;
				_la = TokenStream.LA(1);
				if ( !(_la==Note || _la==Rest) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 99;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==AMPER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VolumeCommandContext : ParserRuleContext {
		public VolumeCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_volumeCommand; } }
	 
		public VolumeCommandContext() { }
		public virtual void CopyFrom(VolumeCommandContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class VolumeContext : VolumeCommandContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Volume() { return GetToken(SfxParser.Volume, 0); }
		public VolumeContext(VolumeCommandContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterVolume(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitVolume(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVolume(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VolumeCommandContext volumeCommand() {
		VolumeCommandContext _localctx = new VolumeCommandContext(Context, State);
		EnterRule(_localctx, 24, RULE_volumeCommand);
		try {
			_localctx = new VolumeContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			Match(Volume);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefaultLengthContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Length() { return GetToken(SfxParser.Length, 0); }
		public DefaultLengthContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_defaultLength; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterDefaultLength(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitDefaultLength(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefaultLength(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefaultLengthContext defaultLength() {
		DefaultLengthContext _localctx = new DefaultLengthContext(Context, State);
		EnterRule(_localctx, 26, RULE_defaultLength);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103;
			Match(Length);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstrumentCommandContext : ParserRuleContext {
		public InstrumentCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instrumentCommand; } }
	 
		public InstrumentCommandContext() { }
		public virtual void CopyFrom(InstrumentCommandContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class InstrumentContext : InstrumentCommandContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Instrument() { return GetToken(SfxParser.Instrument, 0); }
		public InstrumentContext(InstrumentCommandContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterInstrument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitInstrument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstrument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstrumentCommandContext instrumentCommand() {
		InstrumentCommandContext _localctx = new InstrumentCommandContext(Context, State);
		EnterRule(_localctx, 28, RULE_instrumentCommand);
		try {
			_localctx = new InstrumentContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			Match(Instrument);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TripletContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(SfxParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(SfxParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NoteContext[] note() {
			return GetRuleContexts<NoteContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NoteContext note(int i) {
			return GetRuleContext<NoteContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RestContext[] rest() {
			return GetRuleContexts<RestContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RestContext rest(int i) {
			return GetRuleContext<RestContext>(i);
		}
		public TripletContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_triplet; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterTriplet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitTriplet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTriplet(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TripletContext triplet() {
		TripletContext _localctx = new TripletContext(Context, State);
		EnterRule(_localctx, 30, RULE_triplet);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 107;
			Match(LBRACE);
			State = 110;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Note:
				{
				State = 108;
				note();
				}
				break;
			case Rest:
				{
				State = 109;
				rest();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 114;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Note:
				{
				State = 112;
				note();
				}
				break;
			case Rest:
				{
				State = 113;
				rest();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 118;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Note:
				{
				State = 116;
				note();
				}
				break;
			case Rest:
				{
				State = 117;
				rest();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 120;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NakedTieContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Tie() { return GetToken(SfxParser.Tie, 0); }
		public NakedTieContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nakedTie; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterNakedTie(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitNakedTie(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNakedTie(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NakedTieContext nakedTie() {
		NakedTieContext _localctx = new NakedTieContext(Context, State);
		EnterRule(_localctx, 32, RULE_nakedTie);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 122;
			Match(Tie);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HexCommandsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DdPitchBlendCommandContext ddPitchBlendCommand() {
			return GetRuleContext<DdPitchBlendCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HexNumberContext hexNumber() {
			return GetRuleContext<HexNumberContext>(0);
		}
		public HexCommandsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hexCommands; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterHexCommands(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitHexCommands(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHexCommands(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HexCommandsContext hexCommands() {
		HexCommandsContext _localctx = new HexCommandsContext(Context, State);
		EnterRule(_localctx, 34, RULE_hexCommands);
		try {
			State = 126;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NDD:
				EnterOuterAlt(_localctx, 1);
				{
				State = 124;
				ddPitchBlendCommand();
				}
				break;
			case HexNumber:
				EnterOuterAlt(_localctx, 2);
				{
				State = 125;
				hexNumber();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DdPitchBlendCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NDD() { return GetToken(SfxParser.NDD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public HexNumberContext[] hexNumber() {
			return GetRuleContexts<HexNumberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public HexNumberContext hexNumber(int i) {
			return GetRuleContext<HexNumberContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DdPitchBlendItemsContext ddPitchBlendItems() {
			return GetRuleContext<DdPitchBlendItemsContext>(0);
		}
		public DdPitchBlendCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ddPitchBlendCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterDdPitchBlendCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitDdPitchBlendCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDdPitchBlendCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DdPitchBlendCommandContext ddPitchBlendCommand() {
		DdPitchBlendCommandContext _localctx = new DdPitchBlendCommandContext(Context, State);
		EnterRule(_localctx, 36, RULE_ddPitchBlendCommand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			Match(NDD);
			State = 129;
			hexNumber();
			State = 132;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case HexNumber:
				{
				State = 130;
				hexNumber();
				}
				break;
			case GT:
			case LT:
			case Note:
			case Octave:
				{
				State = 131;
				ddPitchBlendItems();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DdPitchBlendItemsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NoteContext note() {
			return GetRuleContext<NoteContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OctaveContext[] octave() {
			return GetRuleContexts<OctaveContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OctaveContext octave(int i) {
			return GetRuleContext<OctaveContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RaiseOctaveContext[] raiseOctave() {
			return GetRuleContexts<RaiseOctaveContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RaiseOctaveContext raiseOctave(int i) {
			return GetRuleContext<RaiseOctaveContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LowerOctaveContext[] lowerOctave() {
			return GetRuleContexts<LowerOctaveContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LowerOctaveContext lowerOctave(int i) {
			return GetRuleContext<LowerOctaveContext>(i);
		}
		public DdPitchBlendItemsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ddPitchBlendItems; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterDdPitchBlendItems(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitDdPitchBlendItems(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDdPitchBlendItems(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DdPitchBlendItemsContext ddPitchBlendItems() {
		DdPitchBlendItemsContext _localctx = new DdPitchBlendItemsContext(Context, State);
		EnterRule(_localctx, 38, RULE_ddPitchBlendItems);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 268288L) != 0)) {
				{
				State = 137;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Octave:
					{
					State = 134;
					octave();
					}
					break;
				case GT:
					{
					State = 135;
					raiseOctave();
					}
					break;
				case LT:
					{
					State = 136;
					lowerOctave();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 141;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 142;
			note();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class E0SfxPriorityContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NE0() { return GetToken(SfxParser.NE0, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HexNumber() { return GetToken(SfxParser.HexNumber, 0); }
		public E0SfxPriorityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_e0SfxPriority; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterE0SfxPriority(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitE0SfxPriority(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitE0SfxPriority(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public E0SfxPriorityContext e0SfxPriority() {
		E0SfxPriorityContext _localctx = new E0SfxPriorityContext(Context, State);
		EnterRule(_localctx, 40, RULE_e0SfxPriority);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 144;
			Match(NE0);
			State = 145;
			Match(HexNumber);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HexNumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HexNumber() { return GetToken(SfxParser.HexNumber, 0); }
		public HexNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hexNumber; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.EnterHexNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ISfxListener typedListener = listener as ISfxListener;
			if (typedListener != null) typedListener.ExitHexNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISfxVisitor<TResult> typedVisitor = visitor as ISfxVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHexNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HexNumberContext hexNumber() {
		HexNumberContext _localctx = new HexNumberContext(Context, State);
		EnterRule(_localctx, 42, RULE_hexNumber);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			Match(HexNumber);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,33,150,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		1,0,3,0,46,8,0,1,0,4,0,49,8,0,11,0,12,0,50,1,0,3,0,54,8,0,1,1,1,1,1,1,
		3,1,59,8,1,1,2,1,2,3,2,63,8,2,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,5,1,5,1,5,
		1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,3,5,83,8,5,1,6,1,6,1,7,1,7,1,8,1,8,1,9,
		1,9,1,10,1,10,1,11,1,11,1,11,4,11,98,8,11,11,11,12,11,99,1,12,1,12,1,13,
		1,13,1,14,1,14,1,15,1,15,1,15,3,15,111,8,15,1,15,1,15,3,15,115,8,15,1,
		15,1,15,3,15,119,8,15,1,15,1,15,1,16,1,16,1,17,1,17,3,17,127,8,17,1,18,
		1,18,1,18,1,18,3,18,133,8,18,1,19,1,19,1,19,5,19,138,8,19,10,19,12,19,
		141,9,19,1,19,1,19,1,20,1,20,1,20,1,21,1,21,1,21,0,0,22,0,2,4,6,8,10,12,
		14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,0,1,1,0,16,17,152,0,53,1,
		0,0,0,2,58,1,0,0,0,4,62,1,0,0,0,6,64,1,0,0,0,8,68,1,0,0,0,10,82,1,0,0,
		0,12,84,1,0,0,0,14,86,1,0,0,0,16,88,1,0,0,0,18,90,1,0,0,0,20,92,1,0,0,
		0,22,94,1,0,0,0,24,101,1,0,0,0,26,103,1,0,0,0,28,105,1,0,0,0,30,107,1,
		0,0,0,32,122,1,0,0,0,34,126,1,0,0,0,36,128,1,0,0,0,38,139,1,0,0,0,40,144,
		1,0,0,0,42,147,1,0,0,0,44,46,3,40,20,0,45,44,1,0,0,0,45,46,1,0,0,0,46,
		48,1,0,0,0,47,49,3,2,1,0,48,47,1,0,0,0,49,50,1,0,0,0,50,48,1,0,0,0,50,
		51,1,0,0,0,51,54,1,0,0,0,52,54,5,0,0,1,53,45,1,0,0,0,53,52,1,0,0,0,54,
		1,1,0,0,0,55,59,3,4,2,0,56,59,3,10,5,0,57,59,3,34,17,0,58,55,1,0,0,0,58,
		56,1,0,0,0,58,57,1,0,0,0,59,3,1,0,0,0,60,63,3,6,3,0,61,63,3,8,4,0,62,60,
		1,0,0,0,62,61,1,0,0,0,63,5,1,0,0,0,64,65,5,23,0,0,65,66,5,27,0,0,66,67,
		5,28,0,0,67,7,1,0,0,0,68,69,5,24,0,0,69,70,5,27,0,0,70,9,1,0,0,0,71,83,
		3,22,11,0,72,83,3,12,6,0,73,83,3,14,7,0,74,83,3,16,8,0,75,83,3,18,9,0,
		76,83,3,20,10,0,77,83,3,24,12,0,78,83,3,26,13,0,79,83,3,28,14,0,80,83,
		3,32,16,0,81,83,3,30,15,0,82,71,1,0,0,0,82,72,1,0,0,0,82,73,1,0,0,0,82,
		74,1,0,0,0,82,75,1,0,0,0,82,76,1,0,0,0,82,77,1,0,0,0,82,78,1,0,0,0,82,
		79,1,0,0,0,82,80,1,0,0,0,82,81,1,0,0,0,83,11,1,0,0,0,84,85,5,16,0,0,85,
		13,1,0,0,0,86,87,5,17,0,0,87,15,1,0,0,0,88,89,5,18,0,0,89,17,1,0,0,0,90,
		91,5,12,0,0,91,19,1,0,0,0,92,93,5,11,0,0,93,21,1,0,0,0,94,97,7,0,0,0,95,
		96,5,4,0,0,96,98,7,0,0,0,97,95,1,0,0,0,98,99,1,0,0,0,99,97,1,0,0,0,99,
		100,1,0,0,0,100,23,1,0,0,0,101,102,5,19,0,0,102,25,1,0,0,0,103,104,5,22,
		0,0,104,27,1,0,0,0,105,106,5,21,0,0,106,29,1,0,0,0,107,110,5,5,0,0,108,
		111,3,12,6,0,109,111,3,14,7,0,110,108,1,0,0,0,110,109,1,0,0,0,111,114,
		1,0,0,0,112,115,3,12,6,0,113,115,3,14,7,0,114,112,1,0,0,0,114,113,1,0,
		0,0,115,118,1,0,0,0,116,119,3,12,6,0,117,119,3,14,7,0,118,116,1,0,0,0,
		118,117,1,0,0,0,119,120,1,0,0,0,120,121,5,6,0,0,121,31,1,0,0,0,122,123,
		5,20,0,0,123,33,1,0,0,0,124,127,3,36,18,0,125,127,3,42,21,0,126,124,1,
		0,0,0,126,125,1,0,0,0,127,35,1,0,0,0,128,129,5,25,0,0,129,132,3,42,21,
		0,130,133,3,42,21,0,131,133,3,38,19,0,132,130,1,0,0,0,132,131,1,0,0,0,
		133,37,1,0,0,0,134,138,3,16,8,0,135,138,3,20,10,0,136,138,3,18,9,0,137,
		134,1,0,0,0,137,135,1,0,0,0,137,136,1,0,0,0,138,141,1,0,0,0,139,137,1,
		0,0,0,139,140,1,0,0,0,140,142,1,0,0,0,141,139,1,0,0,0,142,143,3,12,6,0,
		143,39,1,0,0,0,144,145,5,26,0,0,145,146,5,31,0,0,146,41,1,0,0,0,147,148,
		5,31,0,0,148,43,1,0,0,0,14,45,50,53,58,62,82,99,110,114,118,126,132,137,
		139
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
